version: '3'
services:
    grafana:
        image: grafana/grafana
        ports:
            - "3000:3000"
        environment:
            - GF_INSTALL_PLUGINS=jdbranham-diagram-panel
        volumes:
            - grafana-data:/var/lib/grafana
            - ./datasources:/etc/grafana/provisioning/datasources
    elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
        container_name: elasticsearch
        environment:
          - cluster.name=docker-cluster
          - bootstrap.memory_lock=true
          - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
        ulimits:
          memlock:
            soft: -1
            hard: -1
        ports:
          - 9200:9200

volumes:
  grafana-data: